services:
  mysql:
    image: mysql:8.0
    container_name: pixel38-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pixel38_db
      MYSQL_USER: ali
      MYSQL_PASSWORD: ali123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
